# Generated by Django 5.1 on 2024-08-20 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_item_delete_car'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=40, verbose_name='марка')),
                ('model', models.CharField(max_length=40, verbose_name='модель')),
                ('year', models.IntegerField(verbose_name='год')),
                ('type_fuel', models.CharField(choices=[('бензин', 'Бензин'), ('дизель', 'Дизель'), ('электричество', 'Электричество'), ('гибрид', 'Гибрид')], max_length=13, verbose_name='топливо')),
                ('type_KPP', models.CharField(choices=[('механическая', 'Механическая'), ('автоматическая', 'Автоматическая'), ('вариатор', 'Вариатор'), ('робот', 'Робот')], max_length=14, verbose_name='коробка')),
                ('mileage', models.IntegerField(verbose_name='пробег')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
